version: "3.7"
services:
  db:
    image: postgres:14.8
    container_name: assignment-db
    volumes:
      - ./infrastructure/postgres/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5432
    networks:
      - assignment
  redis:
    image: redis:4.0.14
    container_name: assignment-redis
    # have password root
    command: redis-server --requirepass root
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - assignment
networks:
  assignment:
    driver: bridge