spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5431/assignment_db}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}

  jpa:
    properties:
      hibernate:
        order_inserts: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
        non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE